version: "3"
services:
  redis:
    image: redis
    networks: 
      - webnet
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks: 
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: squibly
  web:
    image: squibly_mvp_server
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    volumes:
      - ./files:/app/files  
    depends_on:
      - db
      - redis  
    command: ["./wait-for-it.sh","-t","0","db:5432", "--", "node", "index.js"]
  nginx:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
      - ./files:/files
    ports:
      - "8080:80"
    networks:
      - webnet
    depends_on:
      - web
    command: /bin/bash -c "cat /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
networks:
  webnet: